### ISSUE TITLE
Compile error in LogWatcher.cs

### ISSUE THREAD

**Issue by LysanderGG** [HearthSim/Hearthstone-Deck-Tracker#3189]
## Bug report
LogWatcher.cs l. 56 `if(!newLines.TryGetValue(line.Time, out var logLines) )`
There is a use of the syntax out var which seems not to be part of C# 6.0 (http://stackoverflow.com/questions/31724163/c-sharp-6-0-tryparse-with-out-var-param)

The code has been added with 9ad33c3afb7a2a4ea38424bab2f6a502267ba062

Am I doing something wrong?

### Expected Behavior
Can compile with C# 6.0

### Actual Behavior
Cannot compile with C# 6.0

### Steps to reproduce behavior
- 

### Log/Screenshots
1>------ Build started: Project: HearthWatcher, Configuration: Debug x86 ------
1>D:\Dev\Hearthstone-Deck-Tracker\HearthWatcher\LogWatcher.cs(56,52,56,60): error CS1003: Syntax error, ',' expected

**Comment by azeier** [comment]
You need C#7 / VS2017.

**Comment by LysanderGG** [comment]
Thank you for you reply.
May I suggest to update https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md then?

**Comment by azeier** [comment]
Good call :) done.
